Controllers films users
DenisLeonenko93/java-filmorate pull request #2
Opened 2023-03-16 17:51 UTC by DenisLeonenko93

2023-03-17 19:18 UTC, z8q requested changes

2023-03-17 19:18 UTC, z8q commented on pom.xml
> +			<artifactId>validation-api</artifactId>
Зависимости `spring-boot-starter-validation` должно быть достаточно.

2023-03-17 19:18 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Проверку тут и в 35-й строке можно выделить в отдельный метод

2023-03-17 19:18 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    String name;
Поля стоит сделать приватными. В User тоже

2023-03-17 19:18 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Data
Эта аннотация состоит из нескольких.
Наставники бывают просят выделить только необходимые,  например `@Getter`, `@Setter`, `@RequiredArgsConstructor`

2023-03-17 19:18 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        users.put(user.getId(), user);
Не хватает логирования

2023-03-17 19:18 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName().isEmpty()) {
Для create и update проверку имени тоже лучше выделить в отдельный метод.

2023-03-19 20:08 UTC, DenisLeonenko93 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        users.put(user.getId(), user);
Исправил

2023-03-19 20:08 UTC, DenisLeonenko93 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Data
Не стал исправлять. Не совсем понял суть замечания.

2023-03-19 20:08 UTC, DenisLeonenko93 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    String name;
Исправил

2023-03-19 20:08 UTC, DenisLeonenko93 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Исправил

2023-03-19 20:09 UTC, DenisLeonenko93 commented on pom.xml
> +			<artifactId>validation-api</artifactId>
Исправил.

2023-03-19 20:09 UTC, DenisLeonenko93 commented
Исправил все замечания, кроме одного, касаемо аннотации @Data

2023-03-20 17:37 UTC, z8q approved these changes

2023-03-20 17:37 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null) {
тут можно было бы объединить:
`if (user.getName() == null || user.getName().isBlank()) {`
            `user.setName(user.getLogin());`
            `log.info("Пользователю с id = {}, установлено имя: {}", user.getId(), user.getName());`
`}`
isBlank() еще проверит на строку, в которой только пробелы – `"     "` вот такую)

2023-03-20 17:37 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Data
Эта аннотация включает в себя несколько других аннотаций. Просто стоит разобраться, из чего состоит

2023-03-20 18:35 UTC, merged