Add database
DenisLeonenko93/java-filmorate pull request #4
Opened 2023-04-26 18:44 UTC by DenisLeonenko93

2023-04-27 18:34 UTC, z8q requested changes

2023-04-28 07:41 UTC, DenisLeonenko93 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      }
Добавил проверку на совпадение. В ответе отправляю id существующего фильма.

2023-04-28 08:26 UTC, DenisLeonenko93 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      public User addFriend(@PathVariable int id, @PathVariable int friendId) {
Исправлено

2023-04-29 10:18 UTC, z8q approved these changes

2023-04-29 17:51 UTC, merged